const extendedMapping = [
  {
    unit: null,
    displayValues: {},
    quickSearchEnabled: false,
    field: 'alias',
    displayName: 'Alias',
    active: false,
    isArray: true,
    rangeStep: 1,
    type: 'keyword',
    gqlId: 'cqdg::Gene::extended::alias',
    primaryKey: false,
  },
  {
    unit: null,
    displayValues: {},
    quickSearchEnabled: false,
    field: 'biotype',
    displayName: 'Biotype',
    active: false,
    isArray: false,
    rangeStep: 1,
    type: 'keyword',
    gqlId: 'cqdg::Gene::extended::biotype',
    primaryKey: false,
  },
  {
    unit: null,
    displayValues: {},
    quickSearchEnabled: false,
    field: 'chromosome',
    displayName: 'Chromosome',
    active: false,
    isArray: false,
    rangeStep: 1,
    type: 'keyword',
    gqlId: 'cqdg::Gene::extended::chromosome',
    primaryKey: false,
  },
  {
    unit: null,
    displayValues: {},
    quickSearchEnabled: false,
    field: 'cosmic',
    displayName: 'Cosmic',
    active: false,
    isArray: false,
    rangeStep: 1,
    type: 'nested',
    gqlId: 'cqdg::Gene::extended::cosmic',
    primaryKey: false,
  },
  {
    unit: null,
    displayValues: {},
    quickSearchEnabled: false,
    field: 'cosmic.tumour_types_germline',
    displayName: 'Cosmic Tumour Types Germline',
    active: false,
    isArray: false,
    rangeStep: 1,
    type: 'keyword',
    gqlId: 'cqdg::Gene::extended::cosmic.tumour_types_germline',
    primaryKey: false,
  },
  {
    unit: null,
    displayValues: {},
    quickSearchEnabled: false,
    field: 'ddd',
    displayName: 'Ddd',
    active: false,
    isArray: false,
    rangeStep: 1,
    type: 'nested',
    gqlId: 'cqdg::Gene::extended::ddd',
    primaryKey: false,
  },
  {
    unit: null,
    displayValues: {},
    quickSearchEnabled: false,
    field: 'ddd.disease_name',
    displayName: 'Ddd Disease Name',
    active: false,
    isArray: false,
    rangeStep: 1,
    type: 'keyword',
    gqlId: 'cqdg::Gene::extended::ddd.disease_name',
    primaryKey: false,
  },
  {
    unit: null,
    displayValues: {},
    quickSearchEnabled: false,
    field: 'ensembl_gene_id',
    displayName: 'Ensembl Gene Id',
    active: false,
    isArray: false,
    rangeStep: 1,
    type: 'id',
    gqlId: 'cqdg::Gene::extended::ensembl_gene_id',
    primaryKey: false,
  },
  {
    unit: null,
    displayValues: {},
    quickSearchEnabled: false,
    field: 'entrez_gene_id',
    displayName: 'Entrez Gene Id',
    active: false,
    isArray: false,
    rangeStep: 1,
    type: 'id',
    gqlId: 'cqdg::Gene::extended::entrez_gene_id',
    primaryKey: false,
  },
  {
    unit: null,
    displayValues: {},
    quickSearchEnabled: false,
    field: 'gnomad',
    displayName: 'Gnomad',
    active: false,
    isArray: false,
    rangeStep: 1,
    type: 'object',
    gqlId: 'cqdg::Gene::extended::gnomad',
    primaryKey: false,
  },
  {
    unit: null,
    displayValues: {},
    quickSearchEnabled: false,
    field: 'gnomad.loeuf',
    displayName: 'Gnomad Loeuf',
    active: false,
    isArray: false,
    rangeStep: 0.01,
    type: 'float',
    gqlId: 'cqdg::Gene::extended::gnomad.loeuf',
    primaryKey: false,
  },
  {
    unit: null,
    displayValues: {},
    quickSearchEnabled: false,
    field: 'gnomad.pli',
    displayName: 'Gnomad Pli',
    active: false,
    isArray: false,
    rangeStep: 0.01,
    type: 'float',
    gqlId: 'cqdg::Gene::extended::gnomad.pli',
    primaryKey: false,
  },
  {
    unit: null,
    displayValues: {},
    quickSearchEnabled: false,
    field: 'hash',
    displayName: 'Hash',
    active: false,
    isArray: false,
    rangeStep: 1,
    type: 'keyword',
    gqlId: 'cqdg::Gene::extended::hash',
    primaryKey: false,
  },
  {
    unit: null,
    displayValues: {},
    quickSearchEnabled: false,
    field: 'hgnc',
    displayName: 'Hgnc',
    active: false,
    isArray: false,
    rangeStep: 1,
    type: 'keyword',
    gqlId: 'cqdg::Gene::extended::hgnc',
    primaryKey: false,
  },
  {
    unit: null,
    displayValues: {},
    quickSearchEnabled: false,
    field: 'hpo',
    displayName: 'Hpo',
    active: false,
    isArray: false,
    rangeStep: 1,
    type: 'nested',
    gqlId: 'cqdg::Gene::extended::hpo',
    primaryKey: false,
  },
  {
    unit: null,
    displayValues: {},
    quickSearchEnabled: false,
    field: 'hpo.hpo_term_id',
    displayName: 'Hpo Hpo Term Id',
    active: false,
    isArray: false,
    rangeStep: 1,
    type: 'id',
    gqlId: 'cqdg::Gene::extended::hpo.hpo_term_id',
    primaryKey: false,
  },
  {
    unit: null,
    displayValues: {},
    quickSearchEnabled: false,
    field: 'hpo.hpo_term_label',
    displayName: 'Hpo Hpo Term Label',
    active: false,
    isArray: false,
    rangeStep: 1,
    type: 'keyword',
    gqlId: 'cqdg::Gene::extended::hpo.hpo_term_label',
    primaryKey: false,
  },
  {
    unit: null,
    displayValues: {},
    quickSearchEnabled: false,
    field: 'hpo.hpo_term_name',
    displayName: 'Hpo Hpo Term Name',
    active: false,
    isArray: false,
    rangeStep: 1,
    type: 'keyword',
    gqlId: 'cqdg::Gene::extended::hpo.hpo_term_name',
    primaryKey: false,
  },
  {
    unit: null,
    displayValues: {},
    quickSearchEnabled: false,
    field: 'location',
    displayName: 'Location',
    active: false,
    isArray: false,
    rangeStep: 1,
    type: 'keyword',
    gqlId: 'cqdg::Gene::extended::location',
    primaryKey: false,
  },
  {
    unit: null,
    displayValues: {},
    quickSearchEnabled: false,
    field: 'name',
    displayName: 'Name',
    active: false,
    isArray: false,
    rangeStep: 1,
    type: 'keyword',
    gqlId: 'cqdg::Gene::extended::name',
    primaryKey: false,
  },
  {
    unit: null,
    displayValues: {},
    quickSearchEnabled: false,
    field: 'omim',
    displayName: 'Omim',
    active: false,
    isArray: false,
    rangeStep: 1,
    type: 'nested',
    gqlId: 'cqdg::Gene::extended::omim',
    primaryKey: false,
  },
  {
    unit: null,
    displayValues: {},
    quickSearchEnabled: false,
    field: 'omim.inheritance',
    displayName: 'Omim Inheritance',
    active: false,
    isArray: false,
    rangeStep: 1,
    type: 'keyword',
    gqlId: 'cqdg::Gene::extended::omim.inheritance',
    primaryKey: false,
  },
  {
    unit: null,
    displayValues: {},
    quickSearchEnabled: false,
    field: 'omim.inheritance_code',
    displayName: 'Omim Inheritance Code',
    active: false,
    isArray: false,
    rangeStep: 1,
    type: 'keyword',
    gqlId: 'cqdg::Gene::extended::omim.inheritance_code',
    primaryKey: false,
  },
  {
    unit: null,
    displayValues: {},
    quickSearchEnabled: false,
    field: 'omim.name',
    displayName: 'Omim Name',
    active: false,
    isArray: false,
    rangeStep: 1,
    type: 'keyword',
    gqlId: 'cqdg::Gene::extended::omim.name',
    primaryKey: false,
  },
  {
    unit: null,
    displayValues: {},
    quickSearchEnabled: false,
    field: 'omim.omim_id',
    displayName: 'Omim Omim Id',
    active: false,
    isArray: false,
    rangeStep: 1,
    type: 'id',
    gqlId: 'cqdg::Gene::extended::omim.omim_id',
    primaryKey: false,
  },
  {
    unit: null,
    displayValues: {},
    quickSearchEnabled: false,
    field: 'omim_gene_id',
    displayName: 'Omim Gene Id',
    active: false,
    isArray: false,
    rangeStep: 1,
    type: 'id',
    gqlId: 'cqdg::Gene::extended::omim_gene_id',
    primaryKey: false,
  },
  {
    unit: null,
    displayValues: {},
    quickSearchEnabled: false,
    field: 'orphanet',
    displayName: 'Orphanet',
    active: false,
    isArray: false,
    rangeStep: 1,
    type: 'nested',
    gqlId: 'cqdg::Gene::extended::orphanet',
    primaryKey: false,
  },
  {
    unit: null,
    displayValues: {},
    quickSearchEnabled: false,
    field: 'orphanet.disorder_id',
    displayName: 'Orphanet Disorder Id',
    active: false,
    isArray: false,
    rangeStep: 1,
    type: 'id',
    gqlId: 'cqdg::Gene::extended::orphanet.disorder_id',
    primaryKey: false,
  },
  {
    unit: null,
    displayValues: {},
    quickSearchEnabled: false,
    field: 'orphanet.inheritance',
    displayName: 'Orphanet Inheritance',
    active: false,
    isArray: false,
    rangeStep: 1,
    type: 'keyword',
    gqlId: 'cqdg::Gene::extended::orphanet.inheritance',
    primaryKey: false,
  },
  {
    unit: null,
    displayValues: {},
    quickSearchEnabled: false,
    field: 'orphanet.panel',
    displayName: 'Orphanet Panel',
    active: false,
    isArray: false,
    rangeStep: 1,
    type: 'keyword',
    gqlId: 'cqdg::Gene::extended::orphanet.panel',
    primaryKey: false,
  },
  {
    unit: null,
    displayValues: {},
    quickSearchEnabled: false,
    field: 'search_text',
    displayName: 'Search Text',
    active: false,
    isArray: false,
    rangeStep: 1,
    type: 'keyword',
    gqlId: 'cqdg::Gene::extended::search_text',
    primaryKey: false,
  },
  {
    unit: null,
    displayValues: {},
    quickSearchEnabled: false,
    field: 'symbol',
    displayName: 'Symbol',
    active: false,
    isArray: false,
    rangeStep: 1,
    type: 'keyword',
    gqlId: 'cqdg::Gene::extended::symbol',
    primaryKey: false,
  },
];

export default extendedMapping;
