const extendedMapping = [
  {
    unit: null,
    displayValues: {},
    quickSearchEnabled: false,
    field: 'alternate',
    displayName: 'Alternate',
    active: false,
    isArray: false,
    rangeStep: 1,
    type: 'keyword',
    gqlId: 'cqdg::Variant::extended::alternate',
    primaryKey: false,
  },
  {
    unit: null,
    displayValues: {},
    quickSearchEnabled: false,
    field: 'assembly_version',
    displayName: 'Assembly Version',
    active: false,
    isArray: false,
    rangeStep: 1,
    type: 'keyword',
    gqlId: 'cqdg::Variant::extended::assembly_version',
    primaryKey: false,
  },
  {
    unit: null,
    displayValues: {},
    quickSearchEnabled: false,
    field: 'chromosome',
    displayName: 'Chromosome',
    active: false,
    isArray: false,
    rangeStep: 1,
    type: 'keyword',
    gqlId: 'cqdg::Variant::extended::chromosome',
    primaryKey: false,
  },
  {
    unit: null,
    displayValues: {},
    quickSearchEnabled: false,
    field: 'clinvar',
    displayName: 'Clinvar',
    active: false,
    isArray: false,
    rangeStep: 1,
    type: 'object',
    gqlId: 'cqdg::Variant::extended::clinvar',
    primaryKey: false,
  },
  {
    unit: null,
    displayValues: {},
    quickSearchEnabled: false,
    field: 'clinvar.clin_sig',
    displayName: 'Clinvar Clin Sig',
    active: false,
    isArray: true,
    rangeStep: 1,
    type: 'keyword',
    gqlId: 'cqdg::Variant::extended::clinvar.clin_sig',
    primaryKey: false,
  },
  {
    unit: null,
    displayValues: {},
    quickSearchEnabled: false,
    field: 'clinvar.clinvar_id',
    displayName: 'Clinvar Clinvar Id',
    active: false,
    isArray: false,
    rangeStep: 1,
    type: 'id',
    gqlId: 'cqdg::Variant::extended::clinvar.clinvar_id',
    primaryKey: false,
  },
  {
    unit: null,
    displayValues: {},
    quickSearchEnabled: false,
    field: 'clinvar.conditions',
    displayName: 'Clinvar Conditions',
    active: false,
    isArray: true,
    rangeStep: 1,
    type: 'keyword',
    gqlId: 'cqdg::Variant::extended::clinvar.conditions',
    primaryKey: false,
  },
  {
    unit: null,
    displayValues: {},
    quickSearchEnabled: false,
    field: 'clinvar.inheritance',
    displayName: 'Clinvar Inheritance',
    active: false,
    isArray: true,
    rangeStep: 1,
    type: 'keyword',
    gqlId: 'cqdg::Variant::extended::clinvar.inheritance',
    primaryKey: false,
  },
  {
    unit: null,
    displayValues: {},
    quickSearchEnabled: false,
    field: 'clinvar.interpretations',
    displayName: 'Clinvar Interpretations',
    active: false,
    isArray: true,
    rangeStep: 1,
    type: 'keyword',
    gqlId: 'cqdg::Variant::extended::clinvar.interpretations',
    primaryKey: false,
  },
  {
    unit: null,
    displayValues: {},
    quickSearchEnabled: false,
    field: 'cmc',
    displayName: 'Cmc',
    active: false,
    isArray: false,
    rangeStep: 1,
    type: 'object',
    gqlId: 'cqdg::Variant::extended::cmc',
    primaryKey: false,
  },
  {
    unit: null,
    displayValues: {},
    quickSearchEnabled: false,
    field: 'cmc.cosmic_id',
    displayName: 'Cmc Cosmic Id',
    active: false,
    isArray: false,
    rangeStep: 1,
    type: 'id',
    gqlId: 'cqdg::Variant::extended::cmc.cosmic_id',
    primaryKey: false,
  },
  {
    unit: null,
    displayValues: {},
    quickSearchEnabled: false,
    field: 'cmc.mutation_url',
    displayName: 'Cmc Mutation Url',
    active: false,
    isArray: false,
    rangeStep: 1,
    type: 'keyword',
    gqlId: 'cqdg::Variant::extended::cmc.mutation_url',
    primaryKey: false,
  },
  {
    unit: null,
    displayValues: {},
    quickSearchEnabled: false,
    field: 'cmc.sample_mutated',
    displayName: 'Cmc Sample Mutated',
    active: false,
    isArray: false,
    rangeStep: 1,
    type: 'integer',
    gqlId: 'cqdg::Variant::extended::cmc.sample_mutated',
    primaryKey: false,
  },
  {
    unit: null,
    displayValues: {},
    quickSearchEnabled: false,
    field: 'cmc.sample_ratio',
    displayName: 'Cmc Sample Ratio',
    active: false,
    isArray: false,
    rangeStep: 0.01,
    type: 'double',
    gqlId: 'cqdg::Variant::extended::cmc.sample_ratio',
    primaryKey: false,
  },
  {
    unit: null,
    displayValues: {},
    quickSearchEnabled: false,
    field: 'cmc.sample_tested',
    displayName: 'Cmc Sample Tested',
    active: false,
    isArray: false,
    rangeStep: 1,
    type: 'integer',
    gqlId: 'cqdg::Variant::extended::cmc.sample_tested',
    primaryKey: false,
  },
  {
    unit: null,
    displayValues: {},
    quickSearchEnabled: false,
    field: 'cmc.shared_aa',
    displayName: 'Cmc Shared Aa',
    active: false,
    isArray: false,
    rangeStep: 1,
    type: 'integer',
    gqlId: 'cqdg::Variant::extended::cmc.shared_aa',
    primaryKey: false,
  },
  {
    unit: null,
    displayValues: {},
    quickSearchEnabled: false,
    field: 'cmc.tier',
    displayName: 'Cmc Tier',
    active: false,
    isArray: false,
    rangeStep: 1,
    type: 'keyword',
    gqlId: 'cqdg::Variant::extended::cmc.tier',
    primaryKey: false,
  },
  {
    unit: null,
    displayValues: {},
    quickSearchEnabled: false,
    field: 'dna_change',
    displayName: 'Dna Change',
    active: false,
    isArray: false,
    rangeStep: 1,
    type: 'keyword',
    gqlId: 'cqdg::Variant::extended::dna_change',
    primaryKey: false,
  },
  {
    unit: null,
    displayValues: {},
    quickSearchEnabled: false,
    field: 'end',
    displayName: 'End',
    active: false,
    isArray: false,
    rangeStep: 1,
    type: 'long',
    gqlId: 'cqdg::Variant::extended::end',
    primaryKey: false,
  },
  {
    unit: null,
    displayValues: {},
    quickSearchEnabled: false,
    field: 'external_frequencies',
    displayName: 'External Frequencies',
    active: false,
    isArray: false,
    rangeStep: 1,
    type: 'object',
    gqlId: 'cqdg::Variant::extended::external_frequencies',
    primaryKey: false,
  },
  {
    unit: null,
    displayValues: {},
    quickSearchEnabled: false,
    field: 'external_frequencies.gnomad_exomes_2_1_1',
    displayName: 'External Frequencies Gnomad Exomes 2 1 1',
    active: false,
    isArray: false,
    rangeStep: 1,
    type: 'object',
    gqlId: 'cqdg::Variant::extended::external_frequencies.gnomad_exomes_2_1_1',
    primaryKey: false,
  },
  {
    unit: null,
    displayValues: {},
    quickSearchEnabled: false,
    field: 'external_frequencies.gnomad_exomes_2_1_1.ac',
    displayName: 'External Frequencies Gnomad Exomes 2 1 1 Ac',
    active: false,
    isArray: false,
    rangeStep: 1,
    type: 'long',
    gqlId: 'cqdg::Variant::extended::external_frequencies.gnomad_exomes_2_1_1.ac',
    primaryKey: false,
  },
  {
    unit: null,
    displayValues: {},
    quickSearchEnabled: false,
    field: 'external_frequencies.gnomad_exomes_2_1_1.af',
    displayName: 'External Frequencies Gnomad Exomes 2 1 1 Af',
    active: false,
    isArray: false,
    rangeStep: 0.01,
    type: 'float',
    gqlId: 'cqdg::Variant::extended::external_frequencies.gnomad_exomes_2_1_1.af',
    primaryKey: false,
  },
  {
    unit: null,
    displayValues: {},
    quickSearchEnabled: false,
    field: 'external_frequencies.gnomad_exomes_2_1_1.an',
    displayName: 'External Frequencies Gnomad Exomes 2 1 1 An',
    active: false,
    isArray: false,
    rangeStep: 1,
    type: 'long',
    gqlId: 'cqdg::Variant::extended::external_frequencies.gnomad_exomes_2_1_1.an',
    primaryKey: false,
  },
  {
    unit: null,
    displayValues: {},
    quickSearchEnabled: false,
    field: 'external_frequencies.gnomad_exomes_2_1_1.hom',
    displayName: 'External Frequencies Gnomad Exomes 2 1 1 Hom',
    active: false,
    isArray: false,
    rangeStep: 1,
    type: 'long',
    gqlId: 'cqdg::Variant::extended::external_frequencies.gnomad_exomes_2_1_1.hom',
    primaryKey: false,
  },
  {
    unit: null,
    displayValues: {},
    quickSearchEnabled: false,
    field: 'external_frequencies.gnomad_genomes_2_1_1',
    displayName: 'External Frequencies Gnomad Genomes 2 1 1',
    active: false,
    isArray: false,
    rangeStep: 1,
    type: 'object',
    gqlId: 'cqdg::Variant::extended::external_frequencies.gnomad_genomes_2_1_1',
    primaryKey: false,
  },
  {
    unit: null,
    displayValues: {},
    quickSearchEnabled: false,
    field: 'external_frequencies.gnomad_genomes_2_1_1.ac',
    displayName: 'External Frequencies Gnomad Genomes 2 1 1 Ac',
    active: false,
    isArray: false,
    rangeStep: 1,
    type: 'long',
    gqlId: 'cqdg::Variant::extended::external_frequencies.gnomad_genomes_2_1_1.ac',
    primaryKey: false,
  },
  {
    unit: null,
    displayValues: {},
    quickSearchEnabled: false,
    field: 'external_frequencies.gnomad_genomes_2_1_1.af',
    displayName: 'External Frequencies Gnomad Genomes 2 1 1 Af',
    active: false,
    isArray: false,
    rangeStep: 0.01,
    type: 'float',
    gqlId: 'cqdg::Variant::extended::external_frequencies.gnomad_genomes_2_1_1.af',
    primaryKey: false,
  },
  {
    unit: null,
    displayValues: {},
    quickSearchEnabled: false,
    field: 'external_frequencies.gnomad_genomes_2_1_1.an',
    displayName: 'External Frequencies Gnomad Genomes 2 1 1 An',
    active: false,
    isArray: false,
    rangeStep: 1,
    type: 'long',
    gqlId: 'cqdg::Variant::extended::external_frequencies.gnomad_genomes_2_1_1.an',
    primaryKey: false,
  },
  {
    unit: null,
    displayValues: {},
    quickSearchEnabled: false,
    field: 'external_frequencies.gnomad_genomes_2_1_1.hom',
    displayName: 'External Frequencies Gnomad Genomes 2 1 1 Hom',
    active: false,
    isArray: false,
    rangeStep: 1,
    type: 'long',
    gqlId: 'cqdg::Variant::extended::external_frequencies.gnomad_genomes_2_1_1.hom',
    primaryKey: false,
  },
  {
    unit: null,
    displayValues: {},
    quickSearchEnabled: false,
    field: 'external_frequencies.gnomad_genomes_3',
    displayName: 'External Frequencies Gnomad Genomes 3',
    active: false,
    isArray: false,
    rangeStep: 1,
    type: 'object',
    gqlId: 'cqdg::Variant::extended::external_frequencies.gnomad_genomes_3',
    primaryKey: false,
  },
  {
    unit: null,
    displayValues: {},
    quickSearchEnabled: false,
    field: 'external_frequencies.gnomad_genomes_3.ac',
    displayName: 'External Frequencies Gnomad Genomes 3 Ac',
    active: false,
    isArray: false,
    rangeStep: 1,
    type: 'long',
    gqlId: 'cqdg::Variant::extended::external_frequencies.gnomad_genomes_3.ac',
    primaryKey: false,
  },
  {
    unit: null,
    displayValues: {},
    quickSearchEnabled: false,
    field: 'external_frequencies.gnomad_genomes_3.af',
    displayName: 'External Frequencies Gnomad Genomes 3 Af',
    active: false,
    isArray: false,
    rangeStep: 0.01,
    type: 'float',
    gqlId: 'cqdg::Variant::extended::external_frequencies.gnomad_genomes_3.af',
    primaryKey: false,
  },
  {
    unit: null,
    displayValues: {},
    quickSearchEnabled: false,
    field: 'external_frequencies.gnomad_genomes_3.an',
    displayName: 'External Frequencies Gnomad Genomes 3 An',
    active: false,
    isArray: false,
    rangeStep: 1,
    type: 'long',
    gqlId: 'cqdg::Variant::extended::external_frequencies.gnomad_genomes_3.an',
    primaryKey: false,
  },
  {
    unit: null,
    displayValues: {},
    quickSearchEnabled: false,
    field: 'external_frequencies.gnomad_genomes_3.hom',
    displayName: 'External Frequencies Gnomad Genomes 3 Hom',
    active: false,
    isArray: false,
    rangeStep: 1,
    type: 'long',
    gqlId: 'cqdg::Variant::extended::external_frequencies.gnomad_genomes_3.hom',
    primaryKey: false,
  },
  {
    unit: null,
    displayValues: {},
    quickSearchEnabled: false,
    field: 'external_frequencies.thousand_genomes',
    displayName: 'External Frequencies Thousand Genomes',
    active: false,
    isArray: false,
    rangeStep: 1,
    type: 'object',
    gqlId: 'cqdg::Variant::extended::external_frequencies.thousand_genomes',
    primaryKey: false,
  },
  {
    unit: null,
    displayValues: {},
    quickSearchEnabled: false,
    field: 'external_frequencies.thousand_genomes.ac',
    displayName: 'External Frequencies Thousand Genomes Ac',
    active: false,
    isArray: false,
    rangeStep: 1,
    type: 'long',
    gqlId: 'cqdg::Variant::extended::external_frequencies.thousand_genomes.ac',
    primaryKey: false,
  },
  {
    unit: null,
    displayValues: {},
    quickSearchEnabled: false,
    field: 'external_frequencies.thousand_genomes.af',
    displayName: 'External Frequencies Thousand Genomes Af',
    active: false,
    isArray: false,
    rangeStep: 0.01,
    type: 'float',
    gqlId: 'cqdg::Variant::extended::external_frequencies.thousand_genomes.af',
    primaryKey: false,
  },
  {
    unit: null,
    displayValues: {},
    quickSearchEnabled: false,
    field: 'external_frequencies.thousand_genomes.an',
    displayName: 'External Frequencies Thousand Genomes An',
    active: false,
    isArray: false,
    rangeStep: 1,
    type: 'long',
    gqlId: 'cqdg::Variant::extended::external_frequencies.thousand_genomes.an',
    primaryKey: false,
  },
  {
    unit: null,
    displayValues: {},
    quickSearchEnabled: false,
    field: 'external_frequencies.topmed_bravo',
    displayName: 'External Frequencies Topmed Bravo',
    active: false,
    isArray: false,
    rangeStep: 1,
    type: 'object',
    gqlId: 'cqdg::Variant::extended::external_frequencies.topmed_bravo',
    primaryKey: false,
  },
  {
    unit: null,
    displayValues: {},
    quickSearchEnabled: false,
    field: 'external_frequencies.topmed_bravo.ac',
    displayName: 'External Frequencies Topmed Bravo Ac',
    active: false,
    isArray: false,
    rangeStep: 1,
    type: 'long',
    gqlId: 'cqdg::Variant::extended::external_frequencies.topmed_bravo.ac',
    primaryKey: false,
  },
  {
    unit: null,
    displayValues: {},
    quickSearchEnabled: false,
    field: 'external_frequencies.topmed_bravo.af',
    displayName: 'External Frequencies Topmed Bravo Af',
    active: false,
    isArray: false,
    rangeStep: 0.01,
    type: 'float',
    gqlId: 'cqdg::Variant::extended::external_frequencies.topmed_bravo.af',
    primaryKey: false,
  },
  {
    unit: null,
    displayValues: {},
    quickSearchEnabled: false,
    field: 'external_frequencies.topmed_bravo.an',
    displayName: 'External Frequencies Topmed Bravo An',
    active: false,
    isArray: false,
    rangeStep: 1,
    type: 'long',
    gqlId: 'cqdg::Variant::extended::external_frequencies.topmed_bravo.an',
    primaryKey: false,
  },
  {
    unit: null,
    displayValues: {},
    quickSearchEnabled: false,
    field: 'external_frequencies.topmed_bravo.het',
    displayName: 'External Frequencies Topmed Bravo Het',
    active: false,
    isArray: false,
    rangeStep: 1,
    type: 'long',
    gqlId: 'cqdg::Variant::extended::external_frequencies.topmed_bravo.het',
    primaryKey: false,
  },
  {
    unit: null,
    displayValues: {},
    quickSearchEnabled: false,
    field: 'external_frequencies.topmed_bravo.hom',
    displayName: 'External Frequencies Topmed Bravo Hom',
    active: false,
    isArray: false,
    rangeStep: 1,
    type: 'long',
    gqlId: 'cqdg::Variant::extended::external_frequencies.topmed_bravo.hom',
    primaryKey: false,
  },
  {
    unit: null,
    displayValues: {},
    quickSearchEnabled: false,
    field: 'gene_external_reference',
    displayName: 'Gene External Reference',
    active: false,
    isArray: true,
    rangeStep: 1,
    type: 'keyword',
    gqlId: 'cqdg::Variant::extended::gene_external_reference',
    primaryKey: false,
  },
  {
    unit: null,
    displayValues: {},
    quickSearchEnabled: false,
    field: 'genes',
    displayName: 'Genes',
    active: false,
    isArray: true,
    rangeStep: 1,
    type: 'nested',
    gqlId: 'cqdg::Variant::extended::genes',
    primaryKey: false,
  },
  {
    unit: null,
    displayValues: {},
    quickSearchEnabled: false,
    field: 'genes.alias',
    displayName: 'Genes Alias',
    active: false,
    isArray: true,
    rangeStep: 1,
    type: 'keyword',
    gqlId: 'cqdg::Variant::extended::genes.alias',
    primaryKey: false,
  },
  {
    unit: null,
    displayValues: {},
    quickSearchEnabled: false,
    field: 'genes.biotype',
    displayName: 'Genes Biotype',
    active: false,
    isArray: false,
    rangeStep: 1,
    type: 'keyword',
    gqlId: 'cqdg::Variant::extended::genes.biotype',
    primaryKey: false,
  },
  {
    unit: null,
    displayValues: {},
    quickSearchEnabled: false,
    field: 'genes.consequences',
    displayName: 'Genes Consequences',
    active: false,
    isArray: false,
    rangeStep: 1,
    type: 'nested',
    gqlId: 'cqdg::Variant::extended::genes.consequences',
    primaryKey: false,
  },
  {
    unit: null,
    displayValues: {},
    quickSearchEnabled: false,
    field: 'genes.consequences.aa_change',
    displayName: 'Genes Consequences Aa Change',
    active: false,
    isArray: false,
    rangeStep: 1,
    type: 'keyword',
    gqlId: 'cqdg::Variant::extended::genes.consequences.aa_change',
    primaryKey: false,
  },
  {
    unit: null,
    displayValues: {},
    quickSearchEnabled: false,
    field: 'genes.consequences.amino_acids',
    displayName: 'Genes Consequences Amino Acids',
    active: false,
    isArray: false,
    rangeStep: 1,
    type: 'object',
    gqlId: 'cqdg::Variant::extended::genes.consequences.amino_acids',
    primaryKey: false,
  },
  {
    unit: null,
    displayValues: {},
    quickSearchEnabled: false,
    field: 'genes.consequences.amino_acids.reference',
    displayName: 'Genes Consequences Amino Acids Reference',
    active: false,
    isArray: false,
    rangeStep: 1,
    type: 'keyword',
    gqlId: 'cqdg::Variant::extended::genes.consequences.amino_acids.reference',
    primaryKey: false,
  },
  {
    unit: null,
    displayValues: {},
    quickSearchEnabled: false,
    field: 'genes.consequences.amino_acids.variant',
    displayName: 'Genes Consequences Amino Acids Variant',
    active: false,
    isArray: false,
    rangeStep: 1,
    type: 'keyword',
    gqlId: 'cqdg::Variant::extended::genes.consequences.amino_acids.variant',
    primaryKey: false,
  },
  {
    unit: null,
    displayValues: {},
    quickSearchEnabled: false,
    field: 'genes.consequences.canonical',
    displayName: 'Genes Consequences Canonical',
    active: false,
    isArray: false,
    rangeStep: 1,
    type: 'boolean',
    gqlId: 'cqdg::Variant::extended::genes.consequences.canonical',
    primaryKey: false,
  },
  {
    unit: null,
    displayValues: {},
    quickSearchEnabled: false,
    field: 'genes.consequences.cdna_position',
    displayName: 'Genes Consequences Cdna Position',
    active: false,
    isArray: false,
    rangeStep: 1,
    type: 'keyword',
    gqlId: 'cqdg::Variant::extended::genes.consequences.cdna_position',
    primaryKey: false,
  },
  {
    unit: null,
    displayValues: {},
    quickSearchEnabled: false,
    field: 'genes.consequences.cds_position',
    displayName: 'Genes Consequences Cds Position',
    active: false,
    isArray: false,
    rangeStep: 1,
    type: 'keyword',
    gqlId: 'cqdg::Variant::extended::genes.consequences.cds_position',
    primaryKey: false,
  },
  {
    unit: null,
    displayValues: {},
    quickSearchEnabled: false,
    field: 'genes.consequences.coding_dna_change',
    displayName: 'Genes Consequences Coding Dna Change',
    active: false,
    isArray: false,
    rangeStep: 1,
    type: 'keyword',
    gqlId: 'cqdg::Variant::extended::genes.consequences.coding_dna_change',
    primaryKey: false,
  },
  {
    unit: null,
    displayValues: {},
    quickSearchEnabled: false,
    field: 'genes.consequences.codons',
    displayName: 'Genes Consequences Codons',
    active: false,
    isArray: false,
    rangeStep: 1,
    type: 'object',
    gqlId: 'cqdg::Variant::extended::genes.consequences.codons',
    primaryKey: false,
  },
  {
    unit: null,
    displayValues: {},
    quickSearchEnabled: false,
    field: 'genes.consequences.codons.reference',
    displayName: 'Genes Consequences Codons Reference',
    active: false,
    isArray: false,
    rangeStep: 1,
    type: 'keyword',
    gqlId: 'cqdg::Variant::extended::genes.consequences.codons.reference',
    primaryKey: false,
  },
  {
    unit: null,
    displayValues: {},
    quickSearchEnabled: false,
    field: 'genes.consequences.codons.variant',
    displayName: 'Genes Consequences Codons Variant',
    active: false,
    isArray: false,
    rangeStep: 1,
    type: 'keyword',
    gqlId: 'cqdg::Variant::extended::genes.consequences.codons.variant',
    primaryKey: false,
  },
  {
    unit: null,
    displayValues: {},
    quickSearchEnabled: false,
    field: 'genes.consequences.consequence',
    displayName: 'Genes Consequences Consequence',
    active: false,
    isArray: true,
    rangeStep: 1,
    type: 'keyword',
    gqlId: 'cqdg::Variant::extended::genes.consequences.consequence',
    primaryKey: false,
  },
  {
    unit: null,
    displayValues: {},
    quickSearchEnabled: false,
    field: 'genes.consequences.conservations',
    displayName: 'Genes Consequences Conservations',
    active: false,
    isArray: false,
    rangeStep: 1,
    type: 'object',
    gqlId: 'cqdg::Variant::extended::genes.consequences.conservations',
    primaryKey: false,
  },
  {
    unit: null,
    displayValues: {},
    quickSearchEnabled: false,
    field: 'genes.consequences.conservations.phyloP100way_vertebrate',
    displayName: 'Genes Consequences Conservations Phylo P 100 Way Vertebrate',
    active: false,
    isArray: false,
    rangeStep: 0.01,
    type: 'float',
    gqlId: 'cqdg::Variant::extended::genes.consequences.conservations.phyloP100way_vertebrate',
    primaryKey: false,
  },
  {
    unit: null,
    displayValues: {},
    quickSearchEnabled: false,
    field: 'genes.consequences.conservations.phyloP17way_primate',
    displayName: 'Genes Consequences Conservations Phylo P 17 Way Primate',
    active: false,
    isArray: false,
    rangeStep: 0.01,
    type: 'float',
    gqlId: 'cqdg::Variant::extended::genes.consequences.conservations.phyloP17way_primate',
    primaryKey: false,
  },
  {
    unit: null,
    displayValues: {},
    quickSearchEnabled: false,
    field: 'genes.consequences.ensembl_feature_id',
    displayName: 'Genes Consequences Ensembl Feature Id',
    active: false,
    isArray: false,
    rangeStep: 1,
    type: 'id',
    gqlId: 'cqdg::Variant::extended::genes.consequences.ensembl_feature_id',
    primaryKey: false,
  },
  {
    unit: null,
    displayValues: {},
    quickSearchEnabled: false,
    field: 'genes.consequences.ensembl_transcript_id',
    displayName: 'Genes Consequences Ensembl Transcript Id',
    active: false,
    isArray: false,
    rangeStep: 1,
    type: 'id',
    gqlId: 'cqdg::Variant::extended::genes.consequences.ensembl_transcript_id',
    primaryKey: false,
  },
  {
    unit: null,
    displayValues: {},
    quickSearchEnabled: false,
    field: 'genes.consequences.exon',
    displayName: 'Genes Consequences Exon',
    active: false,
    isArray: false,
    rangeStep: 1,
    type: 'object',
    gqlId: 'cqdg::Variant::extended::genes.consequences.exon',
    primaryKey: false,
  },
  {
    unit: null,
    displayValues: {},
    quickSearchEnabled: false,
    field: 'genes.consequences.exon.rank',
    displayName: 'Genes Consequences Exon Rank',
    active: false,
    isArray: false,
    rangeStep: 1,
    type: 'keyword',
    gqlId: 'cqdg::Variant::extended::genes.consequences.exon.rank',
    primaryKey: false,
  },
  {
    unit: null,
    displayValues: {},
    quickSearchEnabled: false,
    field: 'genes.consequences.exon.total',
    displayName: 'Genes Consequences Exon Total',
    active: false,
    isArray: false,
    rangeStep: 1,
    type: 'long',
    gqlId: 'cqdg::Variant::extended::genes.consequences.exon.total',
    primaryKey: false,
  },
  {
    unit: null,
    displayValues: {},
    quickSearchEnabled: false,
    field: 'genes.consequences.feature_type',
    displayName: 'Genes Consequences Feature Type',
    active: false,
    isArray: false,
    rangeStep: 1,
    type: 'keyword',
    gqlId: 'cqdg::Variant::extended::genes.consequences.feature_type',
    primaryKey: false,
  },
  {
    unit: null,
    displayValues: {},
    quickSearchEnabled: false,
    field: 'genes.consequences.hgvsc',
    displayName: 'Genes Consequences Hgvsc',
    active: false,
    isArray: false,
    rangeStep: 1,
    type: 'keyword',
    gqlId: 'cqdg::Variant::extended::genes.consequences.hgvsc',
    primaryKey: false,
  },
  {
    unit: null,
    displayValues: {},
    quickSearchEnabled: false,
    field: 'genes.consequences.hgvsp',
    displayName: 'Genes Consequences Hgvsp',
    active: false,
    isArray: false,
    rangeStep: 1,
    type: 'keyword',
    gqlId: 'cqdg::Variant::extended::genes.consequences.hgvsp',
    primaryKey: false,
  },
  {
    unit: null,
    displayValues: {},
    quickSearchEnabled: false,
    field: 'genes.consequences.impact_score',
    displayName: 'Genes Consequences Impact Score',
    active: false,
    isArray: false,
    rangeStep: 1,
    type: 'long',
    gqlId: 'cqdg::Variant::extended::genes.consequences.impact_score',
    primaryKey: false,
  },
  {
    unit: null,
    displayValues: {},
    quickSearchEnabled: false,
    field: 'genes.consequences.intron',
    displayName: 'Genes Consequences Intron',
    active: false,
    isArray: false,
    rangeStep: 1,
    type: 'object',
    gqlId: 'cqdg::Variant::extended::genes.consequences.intron',
    primaryKey: false,
  },
  {
    unit: null,
    displayValues: {},
    quickSearchEnabled: false,
    field: 'genes.consequences.intron.rank',
    displayName: 'Genes Consequences Intron Rank',
    active: false,
    isArray: false,
    rangeStep: 1,
    type: 'keyword',
    gqlId: 'cqdg::Variant::extended::genes.consequences.intron.rank',
    primaryKey: false,
  },
  {
    unit: null,
    displayValues: {},
    quickSearchEnabled: false,
    field: 'genes.consequences.intron.total',
    displayName: 'Genes Consequences Intron Total',
    active: false,
    isArray: false,
    rangeStep: 1,
    type: 'long',
    gqlId: 'cqdg::Variant::extended::genes.consequences.intron.total',
    primaryKey: false,
  },
  {
    unit: null,
    displayValues: {},
    quickSearchEnabled: false,
    field: 'genes.consequences.mane_plus',
    displayName: 'Genes Consequences Mane Plus',
    active: false,
    isArray: false,
    rangeStep: 1,
    type: 'boolean',
    gqlId: 'cqdg::Variant::extended::genes.consequences.mane_plus',
    primaryKey: false,
  },
  {
    unit: null,
    displayValues: {},
    quickSearchEnabled: false,
    field: 'genes.consequences.mane_select',
    displayName: 'Genes Consequences Mane Select',
    active: false,
    isArray: false,
    rangeStep: 1,
    type: 'boolean',
    gqlId: 'cqdg::Variant::extended::genes.consequences.mane_select',
    primaryKey: false,
  },
  {
    unit: null,
    displayValues: {},
    quickSearchEnabled: false,
    field: 'genes.consequences.picked',
    displayName: 'Genes Consequences Picked',
    active: false,
    isArray: false,
    rangeStep: 1,
    type: 'boolean',
    gqlId: 'cqdg::Variant::extended::genes.consequences.picked',
    primaryKey: false,
  },
  {
    unit: null,
    displayValues: {},
    quickSearchEnabled: false,
    field: 'genes.consequences.predictions',
    displayName: 'Genes Consequences Predictions',
    active: false,
    isArray: false,
    rangeStep: 1,
    type: 'object',
    gqlId: 'cqdg::Variant::extended::genes.consequences.predictions',
    primaryKey: false,
  },
  {
    unit: null,
    displayValues: {},
    quickSearchEnabled: false,
    field: 'genes.consequences.predictions.cadd_phred',
    displayName: 'Genes Consequences Predictions Cadd Phred',
    active: false,
    isArray: false,
    rangeStep: 0.01,
    type: 'float',
    gqlId: 'cqdg::Variant::extended::genes.consequences.predictions.cadd_phred',
    primaryKey: false,
  },
  {
    unit: null,
    displayValues: {},
    quickSearchEnabled: false,
    field: 'genes.consequences.predictions.cadd_score',
    displayName: 'Genes Consequences Predictions Cadd Score',
    active: false,
    isArray: false,
    rangeStep: 0.01,
    type: 'float',
    gqlId: 'cqdg::Variant::extended::genes.consequences.predictions.cadd_score',
    primaryKey: false,
  },
  {
    unit: null,
    displayValues: {},
    quickSearchEnabled: false,
    field: 'genes.consequences.predictions.dann_score',
    displayName: 'Genes Consequences Predictions Dann Score',
    active: false,
    isArray: false,
    rangeStep: 0.01,
    type: 'float',
    gqlId: 'cqdg::Variant::extended::genes.consequences.predictions.dann_score',
    primaryKey: false,
  },
  {
    unit: null,
    displayValues: {},
    quickSearchEnabled: false,
    field: 'genes.consequences.predictions.fathmm_pred',
    displayName: 'Genes Consequences Predictions Fathmm Pred',
    active: false,
    isArray: false,
    rangeStep: 1,
    type: 'keyword',
    gqlId: 'cqdg::Variant::extended::genes.consequences.predictions.fathmm_pred',
    primaryKey: false,
  },
  {
    unit: null,
    displayValues: {},
    quickSearchEnabled: false,
    field: 'genes.consequences.predictions.fathmm_score',
    displayName: 'Genes Consequences Predictions Fathmm Score',
    active: false,
    isArray: false,
    rangeStep: 0.01,
    type: 'float',
    gqlId: 'cqdg::Variant::extended::genes.consequences.predictions.fathmm_score',
    primaryKey: false,
  },
  {
    unit: null,
    displayValues: {},
    quickSearchEnabled: false,
    field: 'genes.consequences.predictions.lrt_pred',
    displayName: 'Genes Consequences Predictions Lrt Pred',
    active: false,
    isArray: false,
    rangeStep: 1,
    type: 'keyword',
    gqlId: 'cqdg::Variant::extended::genes.consequences.predictions.lrt_pred',
    primaryKey: false,
  },
  {
    unit: null,
    displayValues: {},
    quickSearchEnabled: false,
    field: 'genes.consequences.predictions.lrt_score',
    displayName: 'Genes Consequences Predictions Lrt Score',
    active: false,
    isArray: false,
    rangeStep: 0.01,
    type: 'float',
    gqlId: 'cqdg::Variant::extended::genes.consequences.predictions.lrt_score',
    primaryKey: false,
  },
  {
    unit: null,
    displayValues: {},
    quickSearchEnabled: false,
    field: 'genes.consequences.predictions.polyphen2_hvar_pred',
    displayName: 'Genes Consequences Predictions Polyphen 2 Hvar Pred',
    active: false,
    isArray: false,
    rangeStep: 1,
    type: 'keyword',
    gqlId: 'cqdg::Variant::extended::genes.consequences.predictions.polyphen2_hvar_pred',
    primaryKey: false,
  },
  {
    unit: null,
    displayValues: {},
    quickSearchEnabled: false,
    field: 'genes.consequences.predictions.polyphen2_hvar_score',
    displayName: 'Genes Consequences Predictions Polyphen 2 Hvar Score',
    active: false,
    isArray: false,
    rangeStep: 0.01,
    type: 'float',
    gqlId: 'cqdg::Variant::extended::genes.consequences.predictions.polyphen2_hvar_score',
    primaryKey: false,
  },
  {
    unit: null,
    displayValues: {},
    quickSearchEnabled: false,
    field: 'genes.consequences.predictions.revel_score',
    displayName: 'Genes Consequences Predictions Revel Score',
    active: false,
    isArray: false,
    rangeStep: 0.01,
    type: 'float',
    gqlId: 'cqdg::Variant::extended::genes.consequences.predictions.revel_score',
    primaryKey: false,
  },
  {
    unit: null,
    displayValues: {},
    quickSearchEnabled: false,
    field: 'genes.consequences.predictions.sift_pred',
    displayName: 'Genes Consequences Predictions Sift Pred',
    active: false,
    isArray: false,
    rangeStep: 1,
    type: 'keyword',
    gqlId: 'cqdg::Variant::extended::genes.consequences.predictions.sift_pred',
    primaryKey: false,
  },
  {
    unit: null,
    displayValues: {},
    quickSearchEnabled: false,
    field: 'genes.consequences.predictions.sift_score',
    displayName: 'Genes Consequences Predictions Sift Score',
    active: false,
    isArray: false,
    rangeStep: 0.01,
    type: 'float',
    gqlId: 'cqdg::Variant::extended::genes.consequences.predictions.sift_score',
    primaryKey: false,
  },
  {
    unit: null,
    displayValues: {},
    quickSearchEnabled: false,
    field: 'genes.consequences.protein_position',
    displayName: 'Genes Consequences Protein Position',
    active: false,
    isArray: false,
    rangeStep: 1,
    type: 'keyword',
    gqlId: 'cqdg::Variant::extended::genes.consequences.protein_position',
    primaryKey: false,
  },
  {
    unit: null,
    displayValues: {},
    quickSearchEnabled: false,
    field: 'genes.consequences.refseq_mrna_id',
    displayName: 'Genes Consequences Refseq Mrna Id',
    active: false,
    isArray: true,
    rangeStep: 1,
    type: 'id',
    gqlId: 'cqdg::Variant::extended::genes.consequences.refseq_mrna_id',
    primaryKey: false,
  },
  {
    unit: null,
    displayValues: {},
    quickSearchEnabled: false,
    field: 'genes.consequences.refseq_protein_id',
    displayName: 'Genes Consequences Refseq Protein Id',
    active: false,
    isArray: false,
    rangeStep: 1,
    type: 'id',
    gqlId: 'cqdg::Variant::extended::genes.consequences.refseq_protein_id',
    primaryKey: false,
  },
  {
    unit: null,
    displayValues: {},
    quickSearchEnabled: false,
    field: 'genes.consequences.strand',
    displayName: 'Genes Consequences Strand',
    active: false,
    isArray: false,
    rangeStep: 1,
    type: 'keyword',
    gqlId: 'cqdg::Variant::extended::genes.consequences.strand',
    primaryKey: false,
  },
  {
    unit: null,
    displayValues: {},
    quickSearchEnabled: false,
    field: 'genes.consequences.uniprot_id',
    displayName: 'Genes Consequences Uniprot Id',
    active: false,
    isArray: false,
    rangeStep: 1,
    type: 'id',
    gqlId: 'cqdg::Variant::extended::genes.consequences.uniprot_id',
    primaryKey: false,
  },
  {
    unit: null,
    displayValues: {},
    quickSearchEnabled: false,
    field: 'genes.consequences.vep_impact',
    displayName: 'Genes Consequences Vep Impact',
    active: false,
    isArray: false,
    rangeStep: 1,
    type: 'keyword',
    gqlId: 'cqdg::Variant::extended::genes.consequences.vep_impact',
    primaryKey: false,
  },
  {
    unit: null,
    displayValues: {},
    quickSearchEnabled: false,
    field: 'genes.cosmic',
    displayName: 'Genes Cosmic',
    active: false,
    isArray: false,
    rangeStep: 1,
    type: 'nested',
    gqlId: 'cqdg::Variant::extended::genes.cosmic',
    primaryKey: false,
  },
  {
    unit: null,
    displayValues: {},
    quickSearchEnabled: false,
    field: 'genes.cosmic.tumour_types_germline',
    displayName: 'Genes Cosmic Tumour Types Germline',
    active: false,
    isArray: true,
    rangeStep: 1,
    type: 'keyword',
    gqlId: 'cqdg::Variant::extended::genes.cosmic.tumour_types_germline',
    primaryKey: false,
  },
  {
    unit: null,
    displayValues: {},
    quickSearchEnabled: false,
    field: 'genes.ddd',
    displayName: 'Genes Ddd',
    active: false,
    isArray: false,
    rangeStep: 1,
    type: 'nested',
    gqlId: 'cqdg::Variant::extended::genes.ddd',
    primaryKey: false,
  },
  {
    unit: null,
    displayValues: {},
    quickSearchEnabled: false,
    field: 'genes.ddd.disease_name',
    displayName: 'Genes Ddd Disease Name',
    active: false,
    isArray: false,
    rangeStep: 1,
    type: 'keyword',
    gqlId: 'cqdg::Variant::extended::genes.ddd.disease_name',
    primaryKey: false,
  },
  {
    unit: null,
    displayValues: {},
    quickSearchEnabled: false,
    field: 'genes.ensembl_gene_id',
    displayName: 'Genes Ensembl Gene Id',
    active: false,
    isArray: false,
    rangeStep: 1,
    type: 'id',
    gqlId: 'cqdg::Variant::extended::genes.ensembl_gene_id',
    primaryKey: false,
  },
  {
    unit: null,
    displayValues: {},
    quickSearchEnabled: false,
    field: 'genes.entrez_gene_id',
    displayName: 'Genes Entrez Gene Id',
    active: false,
    isArray: false,
    rangeStep: 1,
    type: 'id',
    gqlId: 'cqdg::Variant::extended::genes.entrez_gene_id',
    primaryKey: false,
  },
  {
    unit: null,
    displayValues: {},
    quickSearchEnabled: false,
    field: 'genes.gnomad',
    displayName: 'Genes Gnomad',
    active: false,
    isArray: false,
    rangeStep: 1,
    type: 'object',
    gqlId: 'cqdg::Variant::extended::genes.gnomad',
    primaryKey: false,
  },
  {
    unit: null,
    displayValues: {},
    quickSearchEnabled: false,
    field: 'genes.gnomad.loeuf',
    displayName: 'Genes Gnomad Loeuf',
    active: false,
    isArray: false,
    rangeStep: 0.01,
    type: 'float',
    gqlId: 'cqdg::Variant::extended::genes.gnomad.loeuf',
    primaryKey: false,
  },
  {
    unit: null,
    displayValues: {},
    quickSearchEnabled: false,
    field: 'genes.gnomad.pli',
    displayName: 'Genes Gnomad Pli',
    active: false,
    isArray: false,
    rangeStep: 0.01,
    type: 'float',
    gqlId: 'cqdg::Variant::extended::genes.gnomad.pli',
    primaryKey: false,
  },
  {
    unit: null,
    displayValues: {},
    quickSearchEnabled: false,
    field: 'genes.hgnc',
    displayName: 'Genes Hgnc',
    active: false,
    isArray: false,
    rangeStep: 1,
    type: 'keyword',
    gqlId: 'cqdg::Variant::extended::genes.hgnc',
    primaryKey: false,
  },
  {
    unit: null,
    displayValues: {},
    quickSearchEnabled: false,
    field: 'genes.hpo',
    displayName: 'Genes Hpo',
    active: false,
    isArray: false,
    rangeStep: 1,
    type: 'nested',
    gqlId: 'cqdg::Variant::extended::genes.hpo',
    primaryKey: false,
  },
  {
    unit: null,
    displayValues: {},
    quickSearchEnabled: false,
    field: 'genes.hpo.hpo_term_id',
    displayName: 'Genes Hpo Hpo Term Id',
    active: false,
    isArray: false,
    rangeStep: 1,
    type: 'id',
    gqlId: 'cqdg::Variant::extended::genes.hpo.hpo_term_id',
    primaryKey: false,
  },
  {
    unit: null,
    displayValues: {},
    quickSearchEnabled: false,
    field: 'genes.hpo.hpo_term_label',
    displayName: 'Genes Hpo Hpo Term Label',
    active: false,
    isArray: false,
    rangeStep: 1,
    type: 'keyword',
    gqlId: 'cqdg::Variant::extended::genes.hpo.hpo_term_label',
    primaryKey: false,
  },
  {
    unit: null,
    displayValues: {},
    quickSearchEnabled: false,
    field: 'genes.hpo.hpo_term_name',
    displayName: 'Genes Hpo Hpo Term Name',
    active: false,
    isArray: false,
    rangeStep: 1,
    type: 'keyword',
    gqlId: 'cqdg::Variant::extended::genes.hpo.hpo_term_name',
    primaryKey: false,
  },
  {
    unit: null,
    displayValues: {},
    quickSearchEnabled: false,
    field: 'genes.location',
    displayName: 'Genes Location',
    active: false,
    isArray: false,
    rangeStep: 1,
    type: 'keyword',
    gqlId: 'cqdg::Variant::extended::genes.location',
    primaryKey: false,
  },
  {
    unit: null,
    displayValues: {},
    quickSearchEnabled: false,
    field: 'genes.name',
    displayName: 'Genes Name',
    active: false,
    isArray: false,
    rangeStep: 1,
    type: 'keyword',
    gqlId: 'cqdg::Variant::extended::genes.name',
    primaryKey: false,
  },
  {
    unit: null,
    displayValues: {},
    quickSearchEnabled: false,
    field: 'genes.omim',
    displayName: 'Genes Omim',
    active: false,
    isArray: false,
    rangeStep: 1,
    type: 'nested',
    gqlId: 'cqdg::Variant::extended::genes.omim',
    primaryKey: false,
  },
  {
    unit: null,
    displayValues: {},
    quickSearchEnabled: false,
    field: 'genes.omim.inheritance',
    displayName: 'Genes Omim Inheritance',
    active: false,
    isArray: true,
    rangeStep: 1,
    type: 'keyword',
    gqlId: 'cqdg::Variant::extended::genes.omim.inheritance',
    primaryKey: false,
  },
  {
    unit: null,
    displayValues: {},
    quickSearchEnabled: false,
    field: 'genes.omim.inheritance_code',
    displayName: 'Genes Omim Inheritance Code',
    active: false,
    isArray: true,
    rangeStep: 1,
    type: 'keyword',
    gqlId: 'cqdg::Variant::extended::genes.omim.inheritance_code',
    primaryKey: false,
  },
  {
    unit: null,
    displayValues: {},
    quickSearchEnabled: false,
    field: 'genes.omim.name',
    displayName: 'Genes Omim Name',
    active: false,
    isArray: false,
    rangeStep: 1,
    type: 'keyword',
    gqlId: 'cqdg::Variant::extended::genes.omim.name',
    primaryKey: false,
  },
  {
    unit: null,
    displayValues: {},
    quickSearchEnabled: false,
    field: 'genes.omim.omim_id',
    displayName: 'Genes Omim Omim Id',
    active: false,
    isArray: false,
    rangeStep: 1,
    type: 'id',
    gqlId: 'cqdg::Variant::extended::genes.omim.omim_id',
    primaryKey: false,
  },
  {
    unit: null,
    displayValues: {},
    quickSearchEnabled: false,
    field: 'genes.omim_gene_id',
    displayName: 'Genes Omim Gene Id',
    active: false,
    isArray: false,
    rangeStep: 1,
    type: 'id',
    gqlId: 'cqdg::Variant::extended::genes.omim_gene_id',
    primaryKey: false,
  },
  {
    unit: null,
    displayValues: {},
    quickSearchEnabled: false,
    field: 'genes.orphanet',
    displayName: 'Genes Orphanet',
    active: false,
    isArray: false,
    rangeStep: 1,
    type: 'nested',
    gqlId: 'cqdg::Variant::extended::genes.orphanet',
    primaryKey: false,
  },
  {
    unit: null,
    displayValues: {},
    quickSearchEnabled: false,
    field: 'genes.orphanet.disorder_id',
    displayName: 'Genes Orphanet Disorder Id',
    active: false,
    isArray: false,
    rangeStep: 1,
    type: 'id',
    gqlId: 'cqdg::Variant::extended::genes.orphanet.disorder_id',
    primaryKey: false,
  },
  {
    unit: null,
    displayValues: {},
    quickSearchEnabled: false,
    field: 'genes.orphanet.inheritance',
    displayName: 'Genes Orphanet Inheritance',
    active: false,
    isArray: true,
    rangeStep: 1,
    type: 'keyword',
    gqlId: 'cqdg::Variant::extended::genes.orphanet.inheritance',
    primaryKey: false,
  },
  {
    unit: null,
    displayValues: {},
    quickSearchEnabled: false,
    field: 'genes.orphanet.panel',
    displayName: 'Genes Orphanet Panel',
    active: false,
    isArray: false,
    rangeStep: 1,
    type: 'keyword',
    gqlId: 'cqdg::Variant::extended::genes.orphanet.panel',
    primaryKey: false,
  },
  {
    unit: null,
    displayValues: {},
    quickSearchEnabled: false,
    field: 'genes.spliceai',
    displayName: 'Genes Spliceai',
    active: false,
    isArray: false,
    rangeStep: 1,
    type: 'object',
    gqlId: 'cqdg::Variant::extended::genes.spliceai',
    primaryKey: false,
  },
  {
    unit: null,
    displayValues: {},
    quickSearchEnabled: false,
    field: 'genes.spliceai.ds',
    displayName: 'Genes Spliceai Ds',
    active: false,
    isArray: false,
    rangeStep: 0.01,
    type: 'float',
    gqlId: 'cqdg::Variant::extended::genes.spliceai.ds',
    primaryKey: false,
  },
  {
    unit: null,
    displayValues: {},
    quickSearchEnabled: false,
    field: 'genes.spliceai.type',
    displayName: 'Genes Spliceai Type',
    active: false,
    isArray: true,
    rangeStep: 1,
    type: 'keyword',
    gqlId: 'cqdg::Variant::extended::genes.spliceai.type',
    primaryKey: false,
  },
  {
    unit: null,
    displayValues: {},
    quickSearchEnabled: false,
    field: 'genes.symbol',
    displayName: 'Genes Symbol',
    active: false,
    isArray: false,
    rangeStep: 1,
    type: 'keyword',
    gqlId: 'cqdg::Variant::extended::genes.symbol',
    primaryKey: false,
  },
  {
    unit: null,
    displayValues: {},
    quickSearchEnabled: false,
    field: 'hash',
    displayName: 'Hash',
    active: false,
    isArray: false,
    rangeStep: 1,
    type: 'keyword',
    gqlId: 'cqdg::Variant::extended::hash',
    primaryKey: false,
  },
  {
    unit: null,
    displayValues: {},
    quickSearchEnabled: false,
    field: 'hgvsg',
    displayName: 'Hgvsg',
    active: false,
    isArray: false,
    rangeStep: 1,
    type: 'keyword',
    gqlId: 'cqdg::Variant::extended::hgvsg',
    primaryKey: false,
  },
  {
    unit: null,
    displayValues: {},
    quickSearchEnabled: false,
    field: 'internal_frequencies_wgs',
    displayName: 'Internal Frequencies Wgs',
    active: false,
    isArray: false,
    rangeStep: 1,
    type: 'object',
    gqlId: 'cqdg::Variant::extended::internal_frequencies_wgs',
    primaryKey: false,
  },
  {
    unit: null,
    displayValues: {},
    quickSearchEnabled: false,
    field: 'internal_frequencies_wgs.total',
    displayName: 'Internal Frequencies Wgs Total',
    active: false,
    isArray: false,
    rangeStep: 1,
    type: 'object',
    gqlId: 'cqdg::Variant::extended::internal_frequencies_wgs.total',
    primaryKey: false,
  },
  {
    unit: null,
    displayValues: {},
    quickSearchEnabled: false,
    field: 'internal_frequencies_wgs.total.ac',
    displayName: 'Internal Frequencies Wgs Total Ac',
    active: false,
    isArray: false,
    rangeStep: 1,
    type: 'long',
    gqlId: 'cqdg::Variant::extended::internal_frequencies_wgs.total.ac',
    primaryKey: false,
  },
  {
    unit: null,
    displayValues: {},
    quickSearchEnabled: false,
    field: 'internal_frequencies_wgs.total.af',
    displayName: 'Internal Frequencies Wgs Total Af',
    active: false,
    isArray: false,
    rangeStep: 0.01,
    type: 'float',
    gqlId: 'cqdg::Variant::extended::internal_frequencies_wgs.total.af',
    primaryKey: false,
  },
  {
    unit: null,
    displayValues: {},
    quickSearchEnabled: false,
    field: 'internal_frequencies_wgs.total.an',
    displayName: 'Internal Frequencies Wgs Total An',
    active: false,
    isArray: false,
    rangeStep: 1,
    type: 'long',
    gqlId: 'cqdg::Variant::extended::internal_frequencies_wgs.total.an',
    primaryKey: false,
  },
  {
    unit: null,
    displayValues: {},
    quickSearchEnabled: false,
    field: 'internal_frequencies_wgs.total.hom',
    displayName: 'Internal Frequencies Wgs Total Hom',
    active: false,
    isArray: false,
    rangeStep: 1,
    type: 'long',
    gqlId: 'cqdg::Variant::extended::internal_frequencies_wgs.total.hom',
    primaryKey: false,
  },
  {
    unit: null,
    displayValues: {},
    quickSearchEnabled: false,
    field: 'internal_frequencies_wgs.total.pc',
    displayName: 'Internal Frequencies Wgs Total Pc',
    active: false,
    isArray: false,
    rangeStep: 1,
    type: 'long',
    gqlId: 'cqdg::Variant::extended::internal_frequencies_wgs.total.pc',
    primaryKey: false,
  },
  {
    unit: null,
    displayValues: {},
    quickSearchEnabled: false,
    field: 'internal_frequencies_wgs.total.pf',
    displayName: 'Internal Frequencies Wgs Total Pf',
    active: false,
    isArray: false,
    rangeStep: 0.01,
    type: 'float',
    gqlId: 'cqdg::Variant::extended::internal_frequencies_wgs.total.pf',
    primaryKey: false,
  },
  {
    unit: null,
    displayValues: {},
    quickSearchEnabled: false,
    field: 'internal_frequencies_wgs.total.pn',
    displayName: 'Internal Frequencies Wgs Total Pn',
    active: false,
    isArray: false,
    rangeStep: 1,
    type: 'long',
    gqlId: 'cqdg::Variant::extended::internal_frequencies_wgs.total.pn',
    primaryKey: false,
  },
  {
    unit: null,
    displayValues: {},
    quickSearchEnabled: false,
    field: 'locus',
    displayName: 'Locus',
    active: false,
    isArray: false,
    rangeStep: 1,
    type: 'keyword',
    gqlId: 'cqdg::Variant::extended::locus',
    primaryKey: false,
  },
  {
    unit: null,
    displayValues: {},
    quickSearchEnabled: false,
    field: 'max_impact_score',
    displayName: 'Max Impact Score',
    active: false,
    isArray: false,
    rangeStep: 1,
    type: 'long',
    gqlId: 'cqdg::Variant::extended::max_impact_score',
    primaryKey: false,
  },
  {
    unit: null,
    displayValues: {},
    quickSearchEnabled: false,
    field: 'reference',
    displayName: 'Reference',
    active: false,
    isArray: false,
    rangeStep: 1,
    type: 'keyword',
    gqlId: 'cqdg::Variant::extended::reference',
    primaryKey: false,
  },
  {
    unit: null,
    displayValues: {},
    quickSearchEnabled: false,
    field: 'rsnumber',
    displayName: 'Rsnumber',
    active: false,
    isArray: false,
    rangeStep: 1,
    type: 'keyword',
    gqlId: 'cqdg::Variant::extended::rsnumber',
    primaryKey: false,
  },
  {
    unit: null,
    displayValues: {},
    quickSearchEnabled: false,
    field: 'sources',
    displayName: 'Sources',
    active: false,
    isArray: true,
    rangeStep: 1,
    type: 'keyword',
    gqlId: 'cqdg::Variant::extended::sources',
    primaryKey: false,
  },
  {
    unit: null,
    displayValues: {},
    quickSearchEnabled: false,
    field: 'start',
    displayName: 'Start',
    active: false,
    isArray: false,
    rangeStep: 1,
    type: 'long',
    gqlId: 'cqdg::Variant::extended::start',
    primaryKey: false,
  },
  {
    unit: null,
    displayValues: {},
    quickSearchEnabled: false,
    field: 'studies',
    displayName: 'Studies',
    active: false,
    isArray: false,
    rangeStep: 1,
    type: 'nested',
    gqlId: 'cqdg::Variant::extended::studies',
    primaryKey: false,
  },
  {
    unit: null,
    displayValues: {},
    quickSearchEnabled: false,
    field: 'studies.study_code',
    displayName: 'Studies Study Code',
    active: false,
    isArray: false,
    rangeStep: 1,
    type: 'keyword',
    gqlId: 'cqdg::Variant::extended::studies.study_code',
    primaryKey: false,
  },
  {
    unit: null,
    displayValues: {},
    quickSearchEnabled: false,
    field: 'studies.study_id',
    displayName: 'Studies Study Id',
    active: false,
    isArray: false,
    rangeStep: 1,
    type: 'id',
    gqlId: 'cqdg::Variant::extended::studies.study_id',
    primaryKey: false,
  },
  {
    unit: null,
    displayValues: {},
    quickSearchEnabled: false,
    field: 'studies.zygosity',
    displayName: 'Studies Zygosity',
    active: false,
    isArray: true,
    rangeStep: 1,
    type: 'keyword',
    gqlId: 'cqdg::Variant::extended::studies.zygosity',
    primaryKey: false,
  },
  {
    unit: null,
    displayValues: {},
    quickSearchEnabled: false,
    field: 'study_frequencies_wgs',
    displayName: 'Study Frequencies Wgs',
    active: false,
    isArray: false,
    rangeStep: 1,
    type: 'nested',
    gqlId: 'cqdg::Variant::extended::study_frequencies_wgs',
    primaryKey: false,
  },
  {
    unit: null,
    displayValues: {},
    quickSearchEnabled: false,
    field: 'study_frequencies_wgs.study_code',
    displayName: 'Study Frequencies Wgs Study Code',
    active: false,
    isArray: false,
    rangeStep: 1,
    type: 'keyword',
    gqlId: 'cqdg::Variant::extended::study_frequencies_wgs.study_code',
    primaryKey: false,
  },
  {
    unit: null,
    displayValues: {},
    quickSearchEnabled: false,
    field: 'study_frequencies_wgs.study_id',
    displayName: 'Study Frequencies Wgs Study Id',
    active: false,
    isArray: false,
    rangeStep: 1,
    type: 'id',
    gqlId: 'cqdg::Variant::extended::study_frequencies_wgs.study_id',
    primaryKey: false,
  },
  {
    unit: null,
    displayValues: {},
    quickSearchEnabled: false,
    field: 'study_frequencies_wgs.total',
    displayName: 'Study Frequencies Wgs Total',
    active: false,
    isArray: false,
    rangeStep: 1,
    type: 'object',
    gqlId: 'cqdg::Variant::extended::study_frequencies_wgs.total',
    primaryKey: false,
  },
  {
    unit: null,
    displayValues: {},
    quickSearchEnabled: false,
    field: 'study_frequencies_wgs.total.ac',
    displayName: 'Study Frequencies Wgs Total Ac',
    active: false,
    isArray: false,
    rangeStep: 1,
    type: 'long',
    gqlId: 'cqdg::Variant::extended::study_frequencies_wgs.total.ac',
    primaryKey: false,
  },
  {
    unit: null,
    displayValues: {},
    quickSearchEnabled: false,
    field: 'study_frequencies_wgs.total.af',
    displayName: 'Study Frequencies Wgs Total Af',
    active: false,
    isArray: false,
    rangeStep: 0.01,
    type: 'float',
    gqlId: 'cqdg::Variant::extended::study_frequencies_wgs.total.af',
    primaryKey: false,
  },
  {
    unit: null,
    displayValues: {},
    quickSearchEnabled: false,
    field: 'study_frequencies_wgs.total.an',
    displayName: 'Study Frequencies Wgs Total An',
    active: false,
    isArray: false,
    rangeStep: 1,
    type: 'long',
    gqlId: 'cqdg::Variant::extended::study_frequencies_wgs.total.an',
    primaryKey: false,
  },
  {
    unit: null,
    displayValues: {},
    quickSearchEnabled: false,
    field: 'study_frequencies_wgs.total.hom',
    displayName: 'Study Frequencies Wgs Total Hom',
    active: false,
    isArray: false,
    rangeStep: 1,
    type: 'long',
    gqlId: 'cqdg::Variant::extended::study_frequencies_wgs.total.hom',
    primaryKey: false,
  },
  {
    unit: null,
    displayValues: {},
    quickSearchEnabled: false,
    field: 'study_frequencies_wgs.total.pc',
    displayName: 'Study Frequencies Wgs Total Pc',
    active: false,
    isArray: false,
    rangeStep: 1,
    type: 'long',
    gqlId: 'cqdg::Variant::extended::study_frequencies_wgs.total.pc',
    primaryKey: false,
  },
  {
    unit: null,
    displayValues: {},
    quickSearchEnabled: false,
    field: 'study_frequencies_wgs.total.pf',
    displayName: 'Study Frequencies Wgs Total Pf',
    active: false,
    isArray: false,
    rangeStep: 0.01,
    type: 'float',
    gqlId: 'cqdg::Variant::extended::study_frequencies_wgs.total.pf',
    primaryKey: false,
  },
  {
    unit: null,
    displayValues: {},
    quickSearchEnabled: false,
    field: 'study_frequencies_wgs.total.pn',
    displayName: 'Study Frequencies Wgs Total Pn',
    active: false,
    isArray: false,
    rangeStep: 1,
    type: 'long',
    gqlId: 'cqdg::Variant::extended::study_frequencies_wgs.total.pn',
    primaryKey: false,
  },
  {
    unit: null,
    displayValues: {},
    quickSearchEnabled: false,
    field: 'variant_class',
    displayName: 'Variant Class',
    active: false,
    isArray: false,
    rangeStep: 1,
    type: 'keyword',
    gqlId: 'cqdg::Variant::extended::variant_class',
    primaryKey: false,
  },
  {
    unit: null,
    displayValues: {},
    quickSearchEnabled: false,
    field: 'variant_external_reference',
    displayName: 'Variant External Reference',
    active: false,
    isArray: true,
    rangeStep: 1,
    type: 'keyword',
    gqlId: 'cqdg::Variant::extended::variant_external_reference',
    primaryKey: false,
  },

  {
    unit: null,
    displayValues: {},
    quickSearchEnabled: false,
    field: 'external_frequencies.gnomad_genomes_2_1_1',
    displayName: 'External Frequencies Gnomad Genomes 2 1 1',
    active: false,
    isArray: false,
    rangeStep: 1,
    type: 'object',
    gqlId: 'cqdg::Variant::extended::external_frequencies.gnomad_genomes_2_1_1',
    primaryKey: false,
  },
];

export default extendedMapping;
